server:
  port: 80
spring:
  cloud:
    nacos:
      discovery:
        cluster-name: MICROCLOUD_CLUSTER
        namespace: 92bdc18f-074b-47ab-9f40-983fcb4e1ae1
        group: MICROCLOUD_GROUP
        server-addr: nacos-server:8848
        service: ${spring.application.name}
        username: yzb
        password: accp
        register-enabled: false
        metadata:
          author: 易振邦
          age: 17
          sex: 男
  application:
    name: concumer
ribbon:
  eager-load:
    enabled: true
    clients: provider-dept
logging:
  level:
    com.yzb.common.service.IDeptService: debug