server:
  port: 8100
spring:
  application:
    name: turbine
  cloud:
    nacos:
      discovery:
        register-enabled: false
        service: ${spring.application.name}
        server-addr: nacos-server:8848
        namespace: 92bdc18f-074b-47ab-9f40-983fcb4e1ae1
        group: MICROCLOUD_GROUP
        username: yzb
        password: accp
turbine:
  app-config: provider-dept # 配置发现服务名称，从Nacos中获取，多个用逗号隔开
  cluster-name-expression: new String('default') # 表达式用default就好了，按照官方文档