server:
  port: 8002
spring:
  application:
    name: provider-dept
  datasource:
    username: root
    password: accp
    url: jdbc:mysql://localhost:3306/xiaoyi8002?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid: # druid相关配置
      initial-size: 5                # 初始化连接池大小
      min-idle: 10                # 最小维持的连接池大小
      max-active: 50                # 最大支持的连接池大小
      max-wait: 60000                # 最大等待时间（毫秒）
      time-between-eviction-runs-millis: 60000    # 关闭空闲连接间隔（毫秒）
      min-evictable-idle-time-millis: 30000        # 连接最小生存时间（毫秒）
      validation-query: SELECT 1 FROM dual        # 数据库状态检测
      test-while-idle: true            # 申请连接的时候检测连接是否有效
      test-on-borrow: false            # 申请连接时检测连接是否有效
      test-on-return: false            # 归还连接时检测连接是否有效
      pool-prepared-statements: false        # PSCache缓存
      max-pool-prepared-statement-per-connection-size: 20    # 配置PS缓存
      filters: stat, wall, slf4j            # 开启过滤
      stat-view-servlet: # 监控界面配置
        enabled: true    # 启用druid监控界面
        allow: 127.0.0.1    # 设置访问白名单
        login-username: yzhenb   # 用户名
        login-password: 123456    # 密码
        reset-enable: true  # 允许重置
        url-pattern: /druid/*  # 访问路径
      web-stat-filter: # WEB监控
        enabled: true  # 启动URI监控
        url-pattern: /*   # 跟踪根路径下的全部服务
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"    # 跟踪排除
      filter: # Druid过滤器
        slf4j: # 日志
          enabled: true # 启用SLF4j监控
          data-source-log-enabled: true  # 启用数据库日志
          statement-executable-sql-log-enable: true # 执行日志
          result-set-log-enabled: true # ResultSet日志启用
        stat: # SQL监控
          merge-sql: true # 统计时合并相同的SQL命令
          log-slow-sql: true # 当SQL执行缓慢时是否要进行记录
          slow-sql-millis: 1  # 设置慢SQL的执行时间标准，单位：毫秒
        wall: # SQL防火墙
          enabled: true  # 启用SQL防火墙
          config: # 配置防火墙规则
            multi-statement-allow: true # 允许执行批量SQL
            delete-allow: false # 禁止执行删除语句
      aop-patterns: "com.yzb..service.*" # Spring监控
  cloud:
    nacos:
      discovery:
        weight: 20
        cluster-name: MICROCLOUD_CLUSTER
        namespace: 92bdc18f-074b-47ab-9f40-983fcb4e1ae1
        group: MICROCLOUD_GROUP
        server-addr: nacos-server:8848
        service: ${spring.application.name}
        username: yzb
        password: accp
        metadata:
          author: 小易啊
          age: 17
          sex: 男
    sentinel:
      transport:
        port: 8719 # 默认就是8719 微服务与Sentinel的一个整合端口
        dashboard: sentinel-server:8888 # Sentinel 的控制台路径

mybatis-plus:
  #  config-location: classpath:META-INF/mybatis/mybatis-config.xml
  #  mapper-locations: classpath:META-INF/mybatis/mapper/**/*.xml # 所有的mapper映射文件
  type-aliases-package: com.yzb.provider.vo
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0